fragment PageParts on Page {
  header {
    __typename
    title
    subtitle
  }
  section {
    __typename
    ... on PageSectionTextSection {
      body
    }
    ... on PageSectionImageTextSection {
      layout
      body
      image
      alt
    }
    ... on PageSectionVideoSection {
      body
      videoEmbed {
        __typename
        videoUrl
        aspectRatio
      }
    }
  }
}

fragment PostParts on Post {
  title
  body
  seo {
    __typename
    canonical
    metaTitle
    description
    image
    noIndex
  }
}
