fragment PageParts on Page {
  header {
    __typename
    title
    subtitle
  }
  section {
    __typename
    ... on PageSectionTextSection {
      body
    }
    ... on PageSectionImageTextSection {
      body
      image
    }
  }
}

fragment PostParts on Post {
  title
  body
  seo {
    __typename
    canonical
    metaTitle
    description
    image
    noIndex
  }
}
